---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: \.key$
      - id: end-of-file-fixer
        exclude: \.key$
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        exclude: \.key$
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: remove-crlf
        exclude: '\.key$'
      - id: remove-tabs
        exclude: '(postman/.*|\.key$)'
        exclude_types:
          - markdown
